### ISSUE TITLE
no grub

### ISSUE THREAD

**Issue by PenguinOfTheSky** [ivandavidov/minimal-linux-script#21]
error seems to be in this section? total grub failure
In file included from scripts/selinux/genheaders/genheaders.c:19:
./security/selinux/include/classmap.h:249:2: error: #error New address family defined, please update secclass_map.
  249 | #error New address family defined, please update secclass_map.
      |  ^~~~~
make[4]: *** [scripts/Makefile.host:90: scripts/selinux/genheaders/genheaders] Error 1
make[3]: *** [scripts/Makefile.build:544: scripts/selinux/genheaders] Error 2
make[2]: *** [scripts/Makefile.build:544: scripts/selinux] Error 2
make[1]: *** [Makefile:1067: scripts] Error 2
make: *** [Makefile:286: __build_one_by_one] Error 2
cp: cannot stat 'arch/x86/boot/bzImage': No such file or directory

**Comment by ivandavidov** [comment]
The issue seems to be coming from your host environment. Are you using the latest LTS version of Ubuntu or something else? Please be advised that the build scripts have been testes and they work fine, but depending on the host environment (different OS, different toolchain, etc.) some errors may arise and since the host environment is managed by you, it is up to you to research and fix these issues.

**Comment by PenguinOfTheSky** [comment]
version 22.04 lts. looks like i'm missing the 22.04.1 patch. dunno if that makes a difference but i'll give it a shot. maybe do a fresh install in virtualbox w/ubuntu if that's the preferred platform for this code.

**Comment by ivandavidov** [comment]
MLL and MLS both work fine with Ubuntu 22.04 LTS

https://github.com/ivandavidov/minimal/blob/master/.github/workflows/manual.yml

If you are trying to use a newer Linux kernel, then it is possible that this particular kernel requires other dependencies. In that case, you'll need to figure out what's missing on your host machine. Let me know if you manage to fix the issue.
